### ISSUE TITLE
RuntimeError: Input axes must be less than or equal to the product of kernel size and dilation.

### ISSUE THREAD

**Issue by allen89268** [SHI-Labs/NATTEN#122]
I got this RuntimeError when I trained my model. However, when I checked the code in NATTEN/csrc/./include/natten/pytorch/helpers.h , I saw the following code : 
inline void CheckArgsAgainstDim(
    int32_t dim,
    int32_t kernel_size,
    int32_t dilation) {
  TORCH_CHECK(
      kernel_size * dilation <= dim,
      "Input axes must be less than or equal to the product of kernel size and dilation. "
      "Got kernel size ",
      kernel_size,
      ", dilation ",
      dilation,
      ", but dimension size was ",
      dim,
      ".");
}

The code, "kernel_size * dilation <= dim", doesn't match the description, "Input axes must be less than or equal to the product of kernel size and dilation. ".

**Comment by alihassanijr** [comment]
Thank you; yes you are correct. It should read "Input axes must be greater than or equal to the product of kernel size and dilation".

I'll have it fixed in the next release.

**Comment by rashidch** [comment]
Hi,

I still get the same error. 

I have installed `pip3 install natten==0.17.1+torch200cu118 -f https://shi-labs.com/natten/wheels`

RuntimeError: Input axes must be greater than or equal to the product of kernel size and dilation. Got kernel size 3, dilation 1, but dimension size was 2.
Exception raised from CheckArgsAgainstDim at /natten-build/csrc/./include/natten/pytorch/helpers.h:101 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f618ca7a4d7 in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f618ca4436b in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: natten::pytorch::CheckArgsAgainstDim(int, int, int) + 0x9a (0x7f602b3976bf in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/natten/libnatten.cpython-38-x86_64-linux-gnu.so)
frame #3: natten::pytorch::CheckArgsAgainstDim(std::tuple<int> const&, std::tuple<int> const&, std::tuple<int> const&) + 0x4e (0x7f602b39772e in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/natten/libnatten.cpython-38-x86_64-linux-gnu.so)
frame #4: natten::pytorch::na1d_qk_forward(at::Tensor&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, std::tuple<int> const&, std::tuple<int> const&, std::tuple<bool> const&) + 0x300 (0x7f602b395616 in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/natten/libnatten.cpython-38-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x59d454a (0x7f602a3fc54a in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/natten/libnatten.cpython-38-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x59cf60b (0x7f602a3f760b in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/natten/libnatten.cpython-38-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x59c9a0b (0x7f602a3f1a0b in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/natten/libnatten.cpython-38-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x59c9d7a (0x7f602a3f1d7a in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/natten/libnatten.cpython-38-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x301690e (0x7f6027a3e90e in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/natten/libnatten.cpython-38-x86_64-linux-gnu.so)
frame #10: PyCFunction_Call + 0x52 (0x4f5652 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #11: _PyObject_MakeTpCall + 0x3bb (0x4e0c8b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x4df4 (0x4dcde4 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #13: _PyFunction_Vectorcall + 0x106 (0x4e7fe6 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #14: PyObject_Call + 0x24a (0x4f768a in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x1f7b (0x4d9f6b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #16: _PyEval_EvalCodeWithName + 0x2f1 (0x4d6fb1 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #17: _PyFunction_Vectorcall + 0x19c (0x4e807c in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #18: PyObject_Call + 0x24a (0x4f768a in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #19: THPFunction_apply(_object*, _object*) + 0x111a (0x7f6174803b2a in /home/rasho/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #20: PyCFunction_Call + 0xe5 (0x4f56e5 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x5c11 (0x4ddc01 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #22: _PyEval_EvalCodeWithName + 0x2f1 (0x4d6fb1 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #23: /home/rasho/anaconda3/envs/openmmlab/bin/python() [0x4f51bb]
frame #24: _PyEval_EvalFrameDefault + 0x49a9 (0x4dc999 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #25: _PyEval_EvalCodeWithName + 0x2f1 (0x4d6fb1 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #26: _PyFunction_Vectorcall + 0x19c (0x4e807c in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #27: _PyEval_EvalFrameDefault + 0x1150 (0x4d9140 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #28: _PyFunction_Vectorcall + 0x106 (0x4e7fe6 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #29: /home/rasho/anaconda3/envs/openmmlab/bin/python() [0x4f5234]
frame #30: PyObject_Call + 0x24a (0x4f768a in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x1f7b (0x4d9f6b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #32: _PyEval_EvalCodeWithName + 0x2f1 (0x4d6fb1 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #33: _PyObject_FastCallDict + 0x21b (0x4e03db in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #34: _PyObject_Call_Prepend + 0x60 (0x4f1fd0 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #35: /home/rasho/anaconda3/envs/openmmlab/bin/python() [0x5ab347]
frame #36: _PyObject_MakeTpCall + 0x3bb (0x4e0c8b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x4df4 (0x4dcde4 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #38: _PyFunction_Vectorcall + 0x106 (0x4e7fe6 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #39: /home/rasho/anaconda3/envs/openmmlab/bin/python() [0x4f5234]
frame #40: PyObject_Call + 0x24a (0x4f768a in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #41: _PyEval_EvalFrameDefault + 0x1f7b (0x4d9f6b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #42: _PyEval_EvalCodeWithName + 0x2f1 (0x4d6fb1 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #43: _PyObject_FastCallDict + 0x21b (0x4e03db in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #44: _PyObject_Call_Prepend + 0x60 (0x4f1fd0 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #45: /home/rasho/anaconda3/envs/openmmlab/bin/python() [0x5ab347]
frame #46: _PyObject_MakeTpCall + 0x3bb (0x4e0c8b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #47: _PyEval_EvalFrameDefault + 0x4907 (0x4dc8f7 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #48: _PyFunction_Vectorcall + 0x106 (0x4e7fe6 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #49: /home/rasho/anaconda3/envs/openmmlab/bin/python() [0x4f5234]
frame #50: PyObject_Call + 0x24a (0x4f768a in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #51: _PyEval_EvalFrameDefault + 0x1f7b (0x4d9f6b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #52: _PyEval_EvalCodeWithName + 0x2f1 (0x4d6fb1 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #53: _PyObject_FastCallDict + 0x21b (0x4e03db in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #54: _PyObject_Call_Prepend + 0x60 (0x4f1fd0 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #55: /home/rasho/anaconda3/envs/openmmlab/bin/python() [0x5ab347]
frame #56: _PyObject_MakeTpCall + 0x3bb (0x4e0c8b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #57: _PyEval_EvalFrameDefault + 0x4907 (0x4dc8f7 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #58: _PyEval_EvalCodeWithName + 0x2f1 (0x4d6fb1 in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #59: _PyFunction_Vectorcall + 0x19c (0x4e807c in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #60: /home/rasho/anaconda3/envs/openmmlab/bin/python() [0x4f5234]
frame #61: PyObject_Call + 0x24a (0x4f768a in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #62: _PyEval_EvalFrameDefault + 0x1f7b (0x4d9f6b in /home/rasho/anaconda3/envs/openmmlab/bin/python)
frame #63: _PyEval_EvalCodeWithName + 0x2f1 (0x4d6fb1 in /home/rasho/anaconda3/envs/openmmlab/bin/python)

**Comment by alihassanijr** [comment]
@rashidch the original issue was about the error message being incorrect, and has been fixed.

I think the issue you're running into is that your input tensors are not in the expected shape, or you're just using too big of a kernel size / dilation combination.

**Comment by rashidch** [comment]
@alihassanijr You are right.
