### ISSUE TITLE
test_autograd_cuda_gemm (test_na1d.NA1DTests) ... NATTEN failure: cutlass error: Error Internal at: 100

### ISSUE THREAD

**Issue by tanbuzheng** [SHI-Labs/NATTEN#42]
Hi, your work is great! May I ask you a question?
I tried to build NATTEN on V100 but failed. My environment is python=3.8, torch=1.10.1, cuda=11.3.
I bulit NATTEN from source and conducted "make WORKERS=2", but when I conduct "make test", it shows:
 Running unit tests
python -m unittest discover -v -s ./tests
test_autograd_cpu (test_na1d.NA1DTests) ... ok
test_autograd_cuda_gemm (test_na1d.NA1DTests) ... NATTEN failure: cutlass error: Error Internal at: 100

Can you help me find out what's causing this?

**Comment by alihassanijr** [comment]
Thank you for your interest.
Unfortunately, it seems like the setup script compiled the GEMM kernels for you by mistake, which it shouldn't have since GEMM kernels only support Ampere and above right now.
Volta (V100 architecture) should be easy enough, but I just haven't gotten around to trying it.

As for the issue, the easy solution is to just build for V100 (SM70):
```
make CUDA_ARCH="7.0"
```

But if you don't mind, could you run this python snippet and share the output?

```python3
import torch

cuda_device = torch.cuda.get_device_properties(torch.cuda.current_device())
sm = cuda_device.major + cuda_device.minor * 0.1

print(f"{cuda_device=}")
print(f"{sm=}")
```

**Comment by tanbuzheng** [comment]
Thank you for your reply！Sorry, I couldn't follow up in time due to time difference.

I have run the python snippet as follows：
```
>>> import torch
>>> cuda_device = torch.cuda.get_device_properties(torch.cuda.current_device())
>>> sm = cuda_device.major + cuda_device.minor * 0.1
>>> print(f"{cuda_device=}")
cuda_device=_CudaDeviceProperties(name='Tesla V100-SXM2-16GB', major=7, minor=0, total_memory=16150MB, multi_processor_count=80)
>>> print(f"{sm=}")
sm=7.0
```

When I try to execute the command：`make CUDA_ARCH="7.0"`， it returns：
```
Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/featurize/work/NATTEN/setup.py", line 199, in <module>
        setup(
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/featurize/work/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/home/featurize/work/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/featurize/work/NATTEN/setup.py", line 153, in build_extension
        cuda_arch_list, n_arch = get_cuda_arch_list(cuda_arch) # Expects xx -- i.e. 86
      File "/home/featurize/work/NATTEN/setup.py", line 120, in get_cuda_arch_list
        return _check_cuda_arch(cuda_arch_list), 1
      File "/home/featurize/work/NATTEN/setup.py", line 110, in _check_cuda_arch
        assert arch >= 8.0 and arch < 10, f"Only SM80 and above is supported at this time, got {arch}."
    AssertionError: Only SM80 and above is supported at this time, got 7.0.
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /cloud/myenv/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/featurize/work/NATTEN/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/featurize/work/NATTEN/
error: subprocess-exited-with-error
```

So, what should I do to avoid this error?
Looking forward to your reply！

**Comment by tanbuzheng** [comment]
I also try to change line 110 in setup.py to：
`assert arch >= 7.0 and arch < 10, f"Only SM80 and above is supported at this time, got {arch}."`
Then re-execute：
`make CUDA_ARCH="7.0"`
It returns：
```
Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/featurize/work/NATTEN/setup.py", line 199, in <module>
        setup(
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/featurize/work/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/home/featurize/work/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/featurize/work/NATTEN/setup.py", line 196, in build_extension
        subprocess.check_call(['make', f"-j{n_workers}"], cwd=self.build_lib)
      File "/cloud/myenv/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j2']' returned non-zero exit status 2.
    Current arch: 70
    error: subprocess-exited-with-error
```

**Comment by alihassanijr** [comment]
Thank you; it looks like I accidentally left an old assert in. 
Just pushed a fix.
Could you please update your branch and try again?

**Comment by tanbuzheng** [comment]
I've tried again but the problem doesn't seem to be resolved.

When I directly execute 
`make CUDA_ARCH="7.0"`
it returns：
```
Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/featurize/work/NATTEN/setup.py", line 37, in <module>
      from torch.utils.cpp_extension import CUDA_HOME, CppExtension, CUDAExtension, IS_MACOS, IS_WINDOWS, _nt_quote_args, SHARED_FLAG, LIB_EXT
  ImportError: cannot import name 'IS_MACOS' from 'torch.utils.cpp_extension' (/cloud/myenv/lib/python3.8/site-packages/torch/utils/cpp_extension.py)
  error: subprocess-exited-with-error

```
Then I set IS_MACOS=0 in setup.py as somebody else did, and try to execute make `CUDA_ARCH="7.0"` agian, it returns:
 ```
/home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: identifier "__halves2bfloat162" is undefined

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(142): error: no instance of overloaded function "__hadd" matches the argument list
                argument types are: (__nv_bfloat16, __nv_bfloat16)

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: identifier "__halves2bfloat162" is undefined

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists

    /home/featurize/work/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(142): error: no instance of overloaded function "__hadd" matches the argument list
```
```
   self.initialize_options()
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/featurize/work/NATTEN/setup.py", line 200, in <module>
        setup(
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/featurize/work/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/home/featurize/work/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/featurize/work/NATTEN/setup.py", line 197, in build_extension
        subprocess.check_call(['make', f"-j{n_workers}"], cwd=self.build_lib)
      File "/cloud/myenv/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j2']' returned non-zero exit status 2.
    Current arch: 70
    error: subprocess-exited-with-error
```

**Comment by tanbuzheng** [comment]
```
7 errors detected in the compilation of "/home/featurize/work/NATTEN/csrc/autogen/src/cuda/naive/source_0.cu".
    make[3]: *** [CMakeFiles/natten.dir/build.make:104: CMakeFiles/natten.dir/autogen/src/cuda/naive/source_0.cu.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    7 errors detected in the compilation of "/home/featurize/work/NATTEN/csrc/autogen/src/cuda/naive/source_1.cu".
    make[3]: *** [CMakeFiles/natten.dir/build.make:118: CMakeFiles/natten.dir/autogen/src/cuda/naive/source_1.cu.o] Error 1
    make[3]: Leaving directory '/home/featurize/work/NATTEN/build/lib.linux-x86_64-cpython-38'
    make[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/natten.dir/all] Error 2
    make[2]: Leaving directory '/home/featurize/work/NATTEN/build/lib.linux-x86_64-cpython-38'
    make[1]: *** [Makefile:91: all] Error 2
    make[1]: Leaving directory '/home/featurize/work/NATTEN/build/lib.linux-x86_64-cpython-38'
    /cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
      self.metadata.version = self._normalize_version(
    /cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************

    !!
      easy_install.initialize_options(self)
    /cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

```

**Comment by alihassanijr** [comment]
It looks like I was wrong in that Volta and Turing CUDA cores at least have BF16 FMA instructions.
In light of this, I've temporarily disabled BF16 for below SM80, and this time I pushed to a branch (which I should've done earlier as well, but I didn't think we'd hit more issues so at the time wasn't worth a separate PR.)

And thank you for bringing up the `IS_MACOS` import failure, looks like not all previous PT versions had that, so I just copied them over into the setup script so they're not imported.

Could you please try building from this branch?

https://github.com/alihassanijr/NATTEN-Torch/tree/volta-fix

Simply:
```
git clone https://github.com/alihassanijr/NATTEN-Torch

cd NATTEN-Torch

git checkout volta-fix

make
```

**Comment by tanbuzheng** [comment]
Hi! Thank you very much！
I have tried again as you suggested.
After executing the command `make`，it returns：
```
[100%] Linking CXX shared library natten/_C.cpython-38-x86_64-linux-gnu.so
    make[3]: warning:  Clock skew detected.  Your build may be incomplete.
    make[3]: Leaving directory '/home/featurize/work/NATTEN-Torch/build/lib.linux-x86_64-cpython-38'
    [100%] Built target natten
    make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    make[2]: Leaving directory '/home/featurize/work/NATTEN-Torch/build/lib.linux-x86_64-cpython-38'
    make[1]: warning:  Clock skew detected.  Your build may be incomplete.
    make[1]: Leaving directory '/home/featurize/work/NATTEN-Torch/build/lib.linux-x86_64-cpython-38'
    Current arch: 70
    copying build/lib.linux-x86_64-cpython-38/natten/_C.cpython-38-x86_64-linux-gnu.so -> src/natten
    Creating /home/featurize/work/myenv/lib/python3.8/site-packages/natten.egg-link (link to src)
    Adding natten 0.14.7.dev0 to easy-install.pth file

    Installed /home/featurize/work/NATTEN-Torch/src
    /cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
      self.metadata.version = self._normalize_version(
    /cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************

    !!
      easy_install.initialize_options(self)
    /cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
WARNING: Ignoring invalid distribution - (/home/featurize/work/myenv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/featurize/work/myenv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution - (/home/featurize/work/myenv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/featurize/work/myenv/lib/python3.8/site-packages)
Successfully installed natten-0.14.7.dev0
make: warning:  Clock skew detected.  Your build may be incomplete.
```
And I also executed the command：
`make test`
it returns：
```
Running unit tests
python -m unittest discover -v -s ./tests
test_autograd_cpu (test_na1d.NA1DTests) ... ok
test_autograd_cuda_gemm (test_na1d.NA1DTests) ... skipped 'NATTEN not compiled with GEMM kernels.'
test_autograd_cuda_naive (test_na1d.NA1DTests) ... ok
test_cpu_vs_cuda (test_na1d.NA1DTests) ... ok
test_autograd_cpu (test_na2d.NA2DTests) ... ok
test_autograd_cuda_gemm (test_na2d.NA2DTests) ... skipped 'NATTEN not compiled with GEMM kernels.'
test_autograd_cuda_naive (test_na2d.NA2DTests) ... ok
test_autograd_cuda_tiled (test_na2d.NA2DTests) ... ok
test_cpu_vs_cuda (test_na2d.NA2DTests) ... ok
test_autograd_cpu (test_na3d.NA3DTests) ... ok
test_autograd_cuda (test_na3d.NA3DTests) ... ok
test_cpu_vs_cuda (test_na3d.NA3DTests) ... ok

----------------------------------------------------------------------
Ran 12 tests in 87.988s

OK (skipped=2)
make: warning:  Clock skew detected.  Your build may be incomplete.
```
It seems to be very close to success, but there are still a few problems.
Looking forward to your reply

**Comment by tanbuzheng** [comment]
By the way, I also try to execute the command `make CUDA_ARCH="7.0"`，but the same problem persists.

**Comment by alihassanijr** [comment]
It looks like it succeeded to me.
It definitely built the shared library, and the tests are all running fine.

The two tests that were skipped were GEMM tests, and GEMM kernels are only available on SM80 at the moment, so it didn't build and didn't test those for you.

I think the make warning is fine -- we're not technically building with make, we're just using it as a build recipe to simplify running the real setup script (which uses cmake under the hood, and if that had failed, there would be no built object and tests would fail).

**Comment by alihassanijr** [comment]
I'll go ahead and merge the fix then. Thanks for your patience and for bringing this to our attention.

**Comment by tanbuzheng** [comment]
Thanks again, I would like to know what the limitations are if GEMM kernels are not available? Is it a speed limit？

**Comment by alihassanijr** [comment]
It is; unfortunately I presently don't have the bandwidth to extend the GEMM kernels to earlier architectures, which means using NATTEN on below SM80 will fall back to our naive kernels. Our naive kernels will in most cases be slower than our GEMM-based kernels for a number of reasons. I'd point to to issue #37 where I went into more details as to exactly why that is.

That said, naive kernels are still useful to train, test, and verify models using neighborhood attention (pretty much most of NAT and DiNAT experiments were done with naive kernels, and the earlier the model we trained, the more limited it was.)

Also note that our 2D kernels have a set of tiled kernels, that are technically not naive, and though not nearly as good as our GEMM kernels, they should give a significant boost to the naive ones. Those kernels are only available when the dimension per attention head is 32, and kernel size is smaller than or equal to 13x13. 

Last note: NATTEN will always try to pick the best available kernel (GEMMs ahead of tiled, and tiled ahead of naive), so you don't have to worry about setting anything, and will build any of the kernels that are supported based on your architecture, which in your case is only tiled and naive. But if you want to explicitly disable any of those, you can, and the function calls for that are in the README.

**Comment by tanbuzheng** [comment]
Ok，I see. Thanks a lot.

**Comment by alihassanijr** [comment]
Actually I might be able to extend the current GEMM kernels to SM70 and above.
I just managed to get fp16 kernels going on SM75, but I don't have any Volta cards availabe.

Would you be open to testing them on your end @tanbuzheng ?

**Comment by tanbuzheng** [comment]
No problem.
I execute the commands 
```
git clone https://github.com/alihassanijr/NATTEN-Torch

cd NATTEN-Torch

git checkout volta-fix

make
```
in sequence

When I execute the command 
`git checkout volta-fix`
it returns：
`error: pathspec 'volta-fix' did not match any file(s) known to git`
When I execute the command 
`make`
it returns：
```
 make[3]: warning:  Clock skew detected.  Your build may be incomplete.
    make[3]: Leaving directory '/home/featurize/work/NATTEN-Torch/build/lib.linux-x86_64-cpython-38'
    [100%] Built target natten
    make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    make[2]: Leaving directory '/home/featurize/work/NATTEN-Torch/build/lib.linux-x86_64-cpython-38'
    make[1]: warning:  Clock skew detected.  Your build may be incomplete.
    make[1]: Leaving directory '/home/featurize/work/NATTEN-Torch/build/lib.linux-x86_64-cpython-38'
    Current arch: 70
    copying build/lib.linux-x86_64-cpython-38/natten/_C.cpython-38-x86_64-linux-gnu.so -> src/natten
    Creating /home/featurize/work/myenv/lib/python3.8/site-packages/natten.egg-link (link to src)
    natten 0.14.7.dev0 is already the active version in easy-install.pth

    Installed /home/featurize/work/NATTEN-Torch/src
    /cloud/myenv/lib/python3.8/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
      self.metadata.version = self._normalize_version(
    /cloud/myenv/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************

    !!
      easy_install.initialize_options(self)
    /cloud/myenv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
WARNING: Ignoring invalid distribution - (/home/featurize/work/myenv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/featurize/work/myenv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution - (/home/featurize/work/myenv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/featurize/work/myenv/lib/python3.8/site-packages)
Successfully installed natten-0.14.7.dev0
make: warning:  Clock skew detected.  Your build may be incomplete.
```
When I execute
`make test`
it returns 
```
make: Warning: File 'Makefile' has modification time 160 s in the future
Running unit tests
python -m unittest discover -v -s ./tests
test_autograd_cpu (test_na1d.NA1DTests) ... ok
test_autograd_cuda_gemm (test_na1d.NA1DTests) ... skipped 'NATTEN not compiled with GEMM kernels.'
test_autograd_cuda_naive (test_na1d.NA1DTests) ... ok
test_cpu_vs_cuda (test_na1d.NA1DTests) ... ok
test_autograd_cpu (test_na2d.NA2DTests) ... ok
test_autograd_cuda_gemm (test_na2d.NA2DTests) ... skipped 'NATTEN not compiled with GEMM kernels.'
test_autograd_cuda_naive (test_na2d.NA2DTests) ... ok
test_autograd_cuda_tiled (test_na2d.NA2DTests) ... ok
test_cpu_vs_cuda (test_na2d.NA2DTests) ... ok
test_autograd_cpu (test_na3d.NA3DTests) ... ok
test_autograd_cuda (test_na3d.NA3DTests) ... ok
test_cpu_vs_cuda (test_na3d.NA3DTests) ... ok

----------------------------------------------------------------------
Ran 12 tests in 80.547s

OK (skipped=2)
make: warning:  Clock skew detected.  Your build may be incomplete.
```
From where I sit the problem is still there.

**Comment by alihassanijr** [comment]
Thank you. I still haven't pushed the changes, and it'll be a different branch. 
I'll post those soon.

**Comment by tanbuzheng** [comment]
Looking forward to your good news.

**Comment by alihassanijr** [comment]
Here you go.
So far SM75 is good to go, just ran all tests successfully on a 2080 Ti.
Looking forward to seeing what happens with Volta.

https://github.com/alihassanijr/NATTEN-Torch/tree/sm75_gemm

Like earlier you'd run:
```
git clone https://github.com/alihassanijr/NATTEN-Torch

cd NATTEN-Torch

git checkout sm75_gemm

make
```
Just note the new branch name: `sm75_gemm`.

**Comment by tanbuzheng** [comment]
Ok, I'll try it again later on the 2080Ti. But still looking forward to it being available for the V100 as that might be more beneficial to me， because we have resource constraints. Any way, thanks a lot!

**Comment by tanbuzheng** [comment]
Hi, I have tried to build it on 2080Ti follow your instructions，but failed.
It returns:
```
 Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File ".../NATTEN-Torch/setup.py", line 213, in <module>
        setup(
      File "/home/../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/.../NATTEN-Torch/setup.py", line 209, in build_extension
        subprocess.check_call(['cmake', cmake_lists_dir] + cmake_args, cwd=self.build_lib)
      File "/home/.../miniconda3/envs/atest2/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/.../NATTEN-Torch/csrc', '-DOUTPUT_FILE_NAME=natten/_C.cpython-38-x86_64-linux-gnu', '-DNATTEN_CUDA_ARCH_LIST=75', '-DNATTEN_TORCH_CUDA_ARCH_LIST=7.5', '-DNATTEN_IS_WINDOWS=0', '-DNATTEN_IS_MAC=0', '-DNATTEN_WITH_AVX=1', '-DNATTEN_WITH_CUDA=1', '-DNATTEN_WITH_CUDA_FP16=1', '-DNATTEN_WITH_CUTLASS=1', '-DNATTEN_CUTLASS_TARGET_SM=75']' returned non-zero exit status 1.
    Current arch: 75
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
```
Do you know how such a mistake is made？

**Comment by alihassanijr** [comment]
There must have been a miscommunication.
It should support V100 now -- I just don't have access to one.
As for the 2080 error, could please share the full error file (`install.out`)?

**Comment by tanbuzheng** [comment]
OK， Then I hope to solve the problem on V100 first.
Do you mean to also execute the command `git checkout sm75_gemm` on v100?

**Comment by tanbuzheng** [comment]
Sorry, maybe I understood it wrong before.
It can be built successfully on v100, but gemm kernels cannot be used yet. Does this mean?
As for 2080Ti，After I execude `make`，it the full error file is：
```
Cleaning up
rm -rf build/ 
rm -rf dist/ 
rm -rf natten.egg-info/ 
rm -rf src/natten/_C.* 
rm -rf __pycache__
rm -rf tests/__pycache__
rm -rf src/__pycache__
rm -rf src/natten/__pycache__
rm -rf src/natten.egg*
rm -rf install.out
Uninstalling NATTEN
pip uninstall -y natten
WARNING: Skipping natten as it is not installed.
Fetching all third party submodules
git submodule update --init --recursive
Submodule 'third_party/cutlass' (https://github.com/NVIDIA/cutlass/) registered for path 'third_party/cutlass'
Cloning into '/home/eee/image_task/NATTEN-Torch/third_party/cutlass'...
Submodule path 'third_party/cutlass': checked out '6f47420213f757831fae65c686aa471749fa8d60'
Installing NATTEN from source
NATTEN_CUDA_ARCH="" NATTEN_N_WORKERS="" pip install -v -e . 2>&1 | tee install.out
Using pip 23.2.1 from /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/pip (python 3.8)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/eee/image_task/NATTEN-Torch
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Building NATTEN with CUDA 113
  Building NATTEN for SM: 7.5
  Number of workers: 16
  running egg_info
  creating /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info
  writing /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/SOURCES.txt'
  /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
    self.metadata.version = self._normalize_version(
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: packaging in /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages (from natten==0.14.7.dev0) (23.0)
DEPRECATION: block 0.0.2 has a non-standard dependency specifier numpy>=1<2. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of block or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: natten
  Running setup.py develop for natten
    Running command python setup.py develop
    Building NATTEN with CUDA 113
    Building NATTEN for SM: 7.5
    Number of workers: 16
    running develop
    running egg_info
    creating src/natten.egg-info
    writing src/natten.egg-info/PKG-INFO
    writing dependency_links to src/natten.egg-info/dependency_links.txt
    writing requirements to src/natten.egg-info/requires.txt
    writing top-level names to src/natten.egg-info/top_level.txt
    writing manifest file 'src/natten.egg-info/SOURCES.txt'
    reading manifest file 'src/natten.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'src/natten.egg-info/SOURCES.txt'
    running build_ext
    -- The CXX compiler identification is GNU 9.4.0
    -- The CUDA compiler identification is NVIDIA 10.2.89
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Detecting CUDA compiler ABI info
    -- Detecting CUDA compiler ABI info - done
    -- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc - skipped
    -- Detecting CUDA compile features
    -- Detecting CUDA compile features - done
    -- Looking for C++ include pthread.h
    -- Looking for C++ include pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found CUDA: /usr/local/cuda-10.2 (found suitable version "10.2", minimum required is "10.2")
    Building NATTEN with CUDA.
    -- Found Python: /home/eee/miniconda3/envs/atest2/bin/python3.8 (found suitable version "3.8.0", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed
    -- Found CUDA: /usr/local/cuda-10.2 (found version "10.2")
    -- Caffe2: CUDA detected: 10.2
    -- Caffe2: CUDA nvcc is: /usr/local/cuda-10.2/bin/nvcc
    -- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.2
    -- Caffe2: Header version is: 10.2
    -- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH)
    CMake Warning at /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:111 (message):
      Caffe2: Cannot find cuDNN library.  Turning the option off
    Call Stack (most recent call first):
      /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
      /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
      CMakeLists.txt:50 (find_package)

    
    -- /usr/local/cuda-10.2/lib64/libnvrtc.so shorthash is 08c4863f
    -- Autodetected CUDA architecture(s):  7.5 7.5 7.5 7.5
    -- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
    CMake Error at /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
      Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
      libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
    Call Stack (most recent call first):
      /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
      CMakeLists.txt:50 (find_package)

    
    -- Configuring incomplete, errors occurred!
    See also "/home/eee/image_task/NATTEN-Torch/build/lib.linux-x86_64-cpython-38/CMakeFiles/CMakeOutput.log".
    See also "/home/eee/image_task/NATTEN-Torch/build/lib.linux-x86_64-cpython-38/CMakeFiles/CMakeError.log".
    /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
      self.metadata.version = self._normalize_version(
    /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************

    !!
      easy_install.initialize_options(self)
    /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/eee/image_task/NATTEN-Torch/setup.py", line 213, in <module>
        setup(
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/eee/image_task/NATTEN-Torch/setup.py", line 209, in build_extension
        subprocess.check_call(['cmake', cmake_lists_dir] + cmake_args, cwd=self.build_lib)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/eee/image_task/NATTEN-Torch/csrc', '-DOUTPUT_FILE_NAME=natten/_C.cpython-38-x86_64-linux-gnu', '-DNATTEN_CUDA_ARCH_LIST=75', '-DNATTEN_TORCH_CUDA_ARCH_LIST=7.5', '-DNATTEN_IS_WINDOWS=0', '-DNATTEN_IS_MAC=0', '-DNATTEN_WITH_AVX=1', '-DNATTEN_WITH_CUDA=1', '-DNATTEN_WITH_CUDA_FP16=1', '-DNATTEN_WITH_CUTLASS=1', '-DNATTEN_CUTLASS_TARGET_SM=75']' returned non-zero exit status 1.
    Current arch: 75
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/eee/miniconda3/envs/atest2/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/eee/image_task/NATTEN-Torch/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/eee/image_task/NATTEN-Torch/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by alihassanijr** [comment]
I'm not sure I understand, what exactly is the issue with V100?

As for 2080, please share the `install.out` file dumped into the directory; the standard output you shared does not indicate any specific error.

**Comment by tanbuzheng** [comment]
Sorry, I misunderstood. Here, I have provided the install.out file：
```
Using pip 23.2.1 from /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/pip (python 3.8)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/eee/image_task/NATTEN-Torch
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Building NATTEN with CUDA 113
  Building NATTEN for SM: 7.5
  Number of workers: 16
  running egg_info
  creating /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info
  writing /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-j48b0mo_/natten.egg-info/SOURCES.txt'
  /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
    self.metadata.version = self._normalize_version(
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: packaging in /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages (from natten==0.14.7.dev0) (23.0)
DEPRECATION: block 0.0.2 has a non-standard dependency specifier numpy>=1<2. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of block or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: natten
  Running setup.py develop for natten
    Running command python setup.py develop
    Building NATTEN with CUDA 113
    Building NATTEN for SM: 7.5
    Number of workers: 16
    running develop
    running egg_info
    creating src/natten.egg-info
    writing src/natten.egg-info/PKG-INFO
    writing dependency_links to src/natten.egg-info/dependency_links.txt
    writing requirements to src/natten.egg-info/requires.txt
    writing top-level names to src/natten.egg-info/top_level.txt
    writing manifest file 'src/natten.egg-info/SOURCES.txt'
    reading manifest file 'src/natten.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'src/natten.egg-info/SOURCES.txt'
    running build_ext
    -- The CXX compiler identification is GNU 9.4.0
    -- The CUDA compiler identification is NVIDIA 10.2.89
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Detecting CUDA compiler ABI info
    -- Detecting CUDA compiler ABI info - done
    -- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc - skipped
    -- Detecting CUDA compile features
    -- Detecting CUDA compile features - done
    -- Looking for C++ include pthread.h
    -- Looking for C++ include pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found CUDA: /usr/local/cuda-10.2 (found suitable version "10.2", minimum required is "10.2")
    [0mBuilding NATTEN with CUDA.[0m
    -- Found Python: /home/eee/miniconda3/envs/atest2/bin/python3.8 (found suitable version "3.8.0", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed
    -- Found CUDA: /usr/local/cuda-10.2 (found version "10.2")
    -- Caffe2: CUDA detected: 10.2
    -- Caffe2: CUDA nvcc is: /usr/local/cuda-10.2/bin/nvcc
    -- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.2
    -- Caffe2: Header version is: 10.2
    -- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH)
    [33mCMake Warning at /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:111 (message):
      Caffe2: Cannot find cuDNN library.  Turning the option off
    Call Stack (most recent call first):
      /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
      /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
      CMakeLists.txt:50 (find_package)

    [0m
    -- /usr/local/cuda-10.2/lib64/libnvrtc.so shorthash is 08c4863f
    -- Autodetected CUDA architecture(s):  7.5 7.5 7.5 7.5
    -- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
    [31mCMake Error at /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
      Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
      libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
    Call Stack (most recent call first):
      /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
      CMakeLists.txt:50 (find_package)

    [0m
    -- Configuring incomplete, errors occurred!
    See also "/home/eee/image_task/NATTEN-Torch/build/lib.linux-x86_64-cpython-38/CMakeFiles/CMakeOutput.log".
    See also "/home/eee/image_task/NATTEN-Torch/build/lib.linux-x86_64-cpython-38/CMakeFiles/CMakeError.log".
    /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
      self.metadata.version = self._normalize_version(
    /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************

    !!
      easy_install.initialize_options(self)
    /home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/eee/image_task/NATTEN-Torch/setup.py", line 213, in <module>
        setup(
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/eee/image_task/NATTEN-Torch/setup.py", line 209, in build_extension
        subprocess.check_call(['cmake', cmake_lists_dir] + cmake_args, cwd=self.build_lib)
      File "/home/eee/miniconda3/envs/atest2/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/eee/image_task/NATTEN-Torch/csrc', '-DOUTPUT_FILE_NAME=natten/_C.cpython-38-x86_64-linux-gnu', '-DNATTEN_CUDA_ARCH_LIST=75', '-DNATTEN_TORCH_CUDA_ARCH_LIST=7.5', '-DNATTEN_IS_WINDOWS=0', '-DNATTEN_IS_MAC=0', '-DNATTEN_WITH_AVX=1', '-DNATTEN_WITH_CUDA=1', '-DNATTEN_WITH_CUDA_FP16=1', '-DNATTEN_WITH_CUTLASS=1', '-DNATTEN_CUTLASS_TARGET_SM=75']' returned non-zero exit status 1.
    Current arch: 75
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/eee/miniconda3/envs/atest2/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/eee/image_task/NATTEN-Torch/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/eee/image_task/NATTEN-Torch/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by alihassanijr** [comment]
This one looks like it's still the 2080 Ti, and the error is coming from Caffe.
Unfortunately caffe's just a mess to deal with in cmake; I even ran into issues with it when I tried it with conda.

I can't really offer a perfect solution for this particular error, because I can't really reproduce it to begin with.
Your particular environment setup and how your dependencies are set up are what's causing the issue.

You can try and install torch, the cuda toolkit, and cudnn via conda to see whether that'll set up the paths correctly.

**Comment by tanbuzheng** [comment]
OK, thanks. I'll try again later

**Comment by Birch-san** [comment]
@alihassanijr I think compilation still fails for SM75, on latest commit 50a8f77412320d1413cf71a6fd30bfc8074a33bf

https://gist.github.com/Birch-san/216a64bb780ced4a82143aa66574f662

note: I _began_ the compile believing I was scheduled on an A100 (compute arch 8.6), but it looks like the build script was smarter than me and corrected it to SM75.

nevertheless: compilation on SM75 using CUDA 12.2 fails with:

```
    [ 18%] Building CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/1d/sm80/source_1.cu.o
    [ 22%] Building CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_0.cu.o
    [ 27%] Building CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_1.cu.o
    [ 31%] Building CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_2.cu.o
    [ 36%] Building CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_3.cu.o
    [ 40%] Building CUDA object CMakeFiles/natten.dir/autogen/src/cuda/naive/source_0.cu.o
    /p/project/ccstdl/birch1/git/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists
          return __hfma2(a, b, c);
                         ^

    /p/project/ccstdl/birch1/git/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists
          return __hfma2(a, b, c);
                            ^

    /p/project/ccstdl/birch1/git/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(136): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists
          return __hfma2(a, b, c);
                               ^

    /p/project/ccstdl/birch1/git/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists
          return __hfma2(a, __halves2bfloat162(b, b), c);
                         ^

    /p/project/ccstdl/birch1/git/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists
          return __hfma2(a, __halves2bfloat162(b, b), c);
                            ^

    /p/project/ccstdl/birch1/git/NATTEN/csrc/./include/natten/cuda/naive/natten_commons.cuh(139): error: no suitable user-defined conversion from "__nv_bfloat162" to "__half2" exists
          return __hfma2(a, __halves2bfloat162(b, b), c);
```

**Comment by alihassanijr** [comment]
@Birch-san It looks like despite picking the correct SM, it's still trying to compile SM80 kernels, and of course fails on bf16 conversions since bf16 math is only available on SM80 and above. 

Can you try and compile without forcing the arch tag?
It looks like you ran:

```
make CUDA_ARCH="8.6" WORKERS=2
```

But you should probably just run:
```
make CUDA_ARCH="7.5" WORKERS=2
```

or just:
```
make WORKERS=2
```

Let me know if I missed something, and sorry for the late response.

**Comment by alihassanijr** [comment]
The script actually should enforce whatever CUDA arch you specify, and ignore the one it detects. The only element I see referencing SM75 are cmake subs that autodetect that version, but it shouldn't really affect building NATTEN much, but it's always recommended to let it pick the SM to prevent such issues, and if you're using different arch GPUs on the same machine it's definitely recommended to isolate them with Docker, or something similar.
